name: Build

on:
- push

jobs:
  build:
    env:
      NCURSES_VERSION: "6.2"
      NANO_VERSION: "5.8"
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download and Extract Sources
      run: |
        wget https://ftp.gnu.org/pub/gnu/ncurses/ncurses-${{ env.NCURSES_VERSION }}.tar.gz
        wget https://www.nano-editor.org/dist/v5/nano-${{ env.NANO_VERSION }}.tar.xz
    - name: Extract Sources
      run: |
        tar xf nano-${{ env.NANO_VERSION }}.tar.xz
        tar xf ncurses-${{ env.NCURSES_VERSION }}.tar.gz
        mv nano-${{ env.NANO_VERSION }} nano
        mv ncurses-${{ env.NCURSES_VERSION }} ncurses
    - name: Setup QEMU static
      if: matrix.arch != 'amd64'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.arch }}
    - name: Build in Docker
      run: |
        docker buildx build --platform linux/${{ matrix.arch }} -t nano:latest --output type=local,dest=./dest .
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: nano-${{ matrix.arch }}
        path: dest/nano
